### ISSUE TITLE
libuuu/gen/gitversion.h is missing in all recent packaged versions

### ISSUE THREAD

**Issue by JLMorange** [NXPmicro/mfgtools#77]
I tried to build using a pre-packaged version available on https://github.com/NXPmicro/mfgtools/releases
from 1.2.0 till 1.2.39
all fail because libuuu/gen/gitversion.h  is not included
I fixed the build script by using a git version, regenerating the file and re-generating it in my build script
best regards

**Comment by nxpfrankli** [comment]
tar ball can't correct identify source version.  github don't provide customer script to generate it.  which is known issue

**Comment by joerg-krause** [comment]
Why not define a version string in CMakeLists.txt, e.g. using the `project()` command, and use this version string if no git clone is used? This why, both the source tarball and the git clone will compile.

**Comment by FloweyTheFlower420** [comment]
CMakeList.txt can't sync with git tag and commit hash automatically. 
github don't support external script to generate tarball.

**Comment by joerg-krause** [comment]
Maybe I was not clear enough. I've pushed an example to my fork which does apply a version string even when building the source tarball: https://github.com/joerg-krause/mfgtools/tree/gitversion.

**Comment by nxpfrankli** [comment]
If version upgrade 1.2.128,  I have to change CMakeList.txt (project(uuu VERSION 1.2.91)).

**Comment by joerg-krause** [comment]
Yes. Is it a no-go?

**Comment by joerg-krause** [comment]
Another solution would be to add a travis rule to automatically publish a release tarball when tagging a commit. Something like this (totally untested!):

```
jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: skip
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: mfgtools-$TRAVIS_TAG.tar.gz
        overwrite: true
        skip_cleanup: true
        on:
          tags: true
```
